### ISSUE TITLE
feature request: print open tasks

### ISSUE THREAD

**Issue by Ballbump** [creecros/Task2pdf#11]
Printing using this plugin prints only open tasks. I have to print closed tasks. I would be happy to a have an option the filter the tasks I'm going to print.

**Comment by Ballbump** [comment]
I'm not a code-professional. Does anyone have an idea, where/how the open tasks are filtered? I would like to change this filter directly in the code.

**Comment by creecros** [comment]
So, on line 93 of the controller, we get the task id's of the open projects using getAllIds via the taskFinderModel, since status open is the default. You need add the status variable to the line to find the closed tasks.

Example

Current line 93:
        `$task_ids = $this->taskFinderModel->getAllIds($project['id']);`

Change to:
        `$task_ids = $this->taskFinderModel->getAllIds($project['id'], array(TaskModel::STATUS_CLOSED));`

It's been awhile since I have played around in kanboard, but I am pretty sure that would do it.

**Comment by Ballbump** [comment]
Fatal error: Uncaught Error: Class 'Kanboard\Plugin\Task2pdf\Controller\TaskModel' not found in (...)/plugins/Task2pdf/Controller/PrintTaskController.php:93 Stack trace: #0 (...)/app/Core/Controller/Runner.php(77): Kanboard\Plugin\Task2pdf\Controller\PrintTaskController->printProject() #1 (...)/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #2 (...)/index.php(9): Kanboard\Core\Controller\Runner->execute() #3 {main} thrown in (...)/plugins/Task2pdf/Controller/PrintTaskController.php on line 93

**Comment by creecros** [comment]
Add this at the top, where the other `use` are:

`use Kanboard\Model\TaskModel`

**Comment by Ballbump** [comment]
Works fine, thank you very much!
