### ISSUE TITLE
Unsupported encode language

### ISSUE THREAD

**Issue by pieces49** [creecros/Task2pdf#5]
Hi. 

Can you change encode to UTF-8? When I download to PDF my content( wrote by korean ), 

it was broken content.

**Comment by creecros** [comment]
I think I might switch to TCPDF, but it is currently in development of a new deployment, so I will probably wait until that is complete before working on upgrading this plugin. If you know any quick fixes, I would be happy to accept a PR. I tried a few things, that didn't seem to work with dompdf, so for the time being, I probably won't touch this until TCPDF is ready.

https://github.com/tecnickcom/tc-lib-pdf

**Comment by kmahyyg** [comment]
Same problem. The fonts not working with CJK Characters. Maybe you could try to generate PDF using another library or change the default fonts?

Plugin Uninstalled.

**Comment by creecros** [comment]
Or I could add a disclaimer that not all characters are supported until I get around to it.

**Comment by kmahyyg** [comment]
Why not try to just build a page and pop up, then let user use Chrome print feature to convert it to a PDF?

**Comment by creecros** [comment]
It has more to do with I'm a little busy at the moment

**Comment by creecros** [comment]
@kmahyyg @pieces49 i stay ed up figuring this one out last night, with some success. i'll have to add an option, where you can select your print language, maybe in the settings, and then i need to find all the fonts for the cjk languages...more to come, but i did manage to get the simplified chinese to work last night. 

I couldn't ever get it to work before, because i wasn't considering font-weights.

![image](https://user-images.githubusercontent.com/26339368/55952497-c760ca80-5c27-11e9-9131-fb28dbc27bcf.png)

**Comment by creecros** [comment]
https://github.com/creecros/Task2pdf/releases/tag/1.1.0

You will have to toggle on support for CJK Chars. Found in Settings > Application, at the bottom.

**Comment by kmahyyg** [comment]
Thank you so much

**Comment by creecros** [comment]
no problem, let me know if there are issues
